### PR TITLE
Add Shortcut/Navigation Keys

### PR DESCRIPTION
**Pull request by ReblochonMasque**
This addresses issue #142

### CODE REVIEW

**Comment by ReblochonMasque** [comment]
Bump for feedback.
Please let me know if this does not meet the standards, so I can modify it and understand better what your expectations are.
If too busy at this time, please say so too, it is cool, there is no urgency.

**Comment by ReblochonMasque** [comment]
Bumping this again for comments, feedback, merge or close.
Thank you!

**Comment by regebro** [comment]
I know how annoying it is to not get instant feedback. We're all feedback junkies. :-) So sorry about the delay.

**Comment by ReblochonMasque** [comment]
No worries, we all have our own rhythms.
Cheers!

**Pull request merged**
