### PR TITLE
Add new template with Impress 1.0.0

### PR DESCRIPTION
**Pull request by ccamara**
As per issue #154 I have created a rough attempt to add the new toolbar.

Since I am not very confident on my skills nor familiarized with hovercraft yet, and In order not to break things, I created a new template with `impress.js` 1.0.0 and the toolbar, so in order to test this PR hovercraft should call this new template: `hovercraft <filename.rst> --template=templates/impress1.0.0`

### CODE REVIEW

**Comment by ccamara** [comment]
@regebro , I've rebased this PR with latest repo's updates and after b57a36d  checks are passing as well. You may want to merge this PR or make comments to it.

**Comment by tonysyu** [comment]
@ccamara: The example command doesn't work for me, but I might be doing something wrong. When I run `hovercraft <filename.rst> --template=templates/impress1.0.0`, hovercraft looks for a template at `[CURRENT WORKING DIRECTORY]/templates/impress1.0.0` rather than sourcing the template from the hovercraft install. Not sure if that's expected, but I didn't realize that when reading the PR description.

**Comment by tonysyu** [comment]
I also noticed that this seems to break the goto-slide functionality

**Comment by regebro** [comment]
Hi, thanks for this! I've looked at it and used some bits in my branch, but ultimately I got confused by the big changes, so I decided to do it step by step myself so I understand what is going on, even though this of course mostly means doing what you did, albeit perhaps in a different order.

But just because I'm not merging this branch, don't think it wasn't useful!

1.0.0 seems backwards compatible enough so that it doesn't break the examples, so I'm updating the standard templates instead of making a new one, I guess that's the major difference.

**Pull request closed without merging**
