### PR TITLE
Fix links in Examples

### PR DESCRIPTION
**Pull request by ReblochonMasque**
Resolves issue #135

### CODE REVIEW

**Comment by ReblochonMasque** [comment]
Bump for feedback please.

**Comment by ReblochonMasque** [comment]
Bumping this again for comments, feedback, merge or close.
Thank you!

**Comment by regebro** [comment]
This is tricky to fix so it works both on readthedocs and locally (so it's possibly to use local docs from a checkout).

I fixed it by hard-linking to the raw github files. It's hackish but it works.

Thanks for the patch anyway!

**Comment by ReblochonMasque** [comment]
okay, I did not know this could be a problem, sorry.

**Comment by regebro** [comment]
No worries, it made me fix it. :-)

**Pull request closed without merging**
