### PR TITLE
Better support for class names

### PR DESCRIPTION
**Pull request by gdw2**
An attempt to fix https://github.com/regebro/hovercraft/issues/55

### CODE REVIEW

**Comment by kmohrf** [comment]
just implemented this by myself and wanted to submit a pull request. please merge this! :+1:

**Comment by regebro** [comment]
I have to look at this, because the usage of re here seems wrong. This is a traversal of a data tree, you should not have to do regexps on it.

**Comment by gdw2** [comment]
It's just doing regex on the class name.  At any rate, included is a failing test case, so you can test out other solutions.

**Comment by fahhem** [comment]
I've fixed this problem in a different way in #76 and it was merged, so this PR can be closed. I hope that way works for everyone else!

**Comment by regebro** [comment]
Yeah, I for completely irrational reasons like this better.

@gdw2 can you confirm that this solves your problem?

**Pull request closed without merging**
