### PR TITLE
This is how I had to layout substep directives to get the examples wo…

### PR DESCRIPTION
**Pull request by ramiro**
…rking.

### CODE REVIEW

**Comment by regebro** [comment]
OK, I'll take a look.

**Comment by Timoses** [comment]
@ramiro What hovercraft version is this for? 2.6 or master? In 2.6 I can't seem to get substeps working at all. 

Using Firefox, MacOS, hovercraft! as server:
```
----

This paragraph will always be visible

.. class:: substep

    This paragraph will be shown when you press <next>

And this paragraph will also be always visible

.. class:: substep

    And this paragraph will show second

----
```

I haven't tried the `master` branch, though there it would require the impress.js plugin since impress.js `1.0.0`.

**Comment by ramiro** [comment]
> @ramiro What hovercraft version is this for? 2.6 or master? In 2.6 I can't seem to get substeps working at all.

Correct. It's new in 'master' since 2.6 got tagged. See https://github.com/regebro/hovercraft/compare/0b155e3e5bdfab27a27636dd9a4eac59b896dafe...master

**Comment by regebro** [comment]
Thanks, sorry for the delay!

**Pull request merged**
